### ISSUE TITLE
exclude coins  from the  list  

### ISSUE THREAD

**Issue by adam-gweleg** [bennettca/ProfitTrailer-new-binance-listings#2]
1st of all let me thank you for this great  Tool!  

please, i want to know  if there is any way to exclude pair from the list? because after I run jar file and is modified my PARIS file so  I have  2 coins in watch mode.
 
Thanks

**Comment by blindaim** [comment]
I would like to be able to provide an exclude list to this tool so that coins that have been rebranded (like Raiblocks to Nano) and Lisk last year since they are considered new by the bot when rebranded as well. Maybe do a check on coin market cap to see if market capitalization is high for a newly listed coin so rebrands can be excluded?
