### ISSUE TITLE
awesome....buttt....SOM instead of trading disabled

### ISSUE THREAD

**Issue by sethiano** [bennettca/ProfitTrailer-new-binance-listings#3]
I think it would better if you can change it to SOM for the Black list instead of trading disabled, just incase it misses a coin in the very beginning and you get stuck with it.

**Comment by dillonm1075** [comment]
I agree. I'm concerned that if I already have some of those blacklisted coins in bags Ill be stuck with them. The script definitely needs some logic added to recognise that it has to sell those coins first before it blacklists them

**Comment by colinbrinton** [comment]
Absolutely agree. It makes more sense to allow users to sell of bags they may already be holding.

**Comment by daryledesilva** [comment]
som mode instead of disabling trading is now supported with latest rls

**Comment by nmalancea** [comment]
@daryledesilva I think SOM is fixed in the code but not yet packaged in a release (https://github.com/bennettca/binance-auto-blacklist/issues/8#issuecomment-362863247). The `.jar` file doesn't contain the [latest commit](https://github.com/bennettca/binance-auto-blacklist/commit/fb62a8faaa0f1d746573a10b909d154310c25f3d).
cc: @bennettca
